name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn create:npmrc
        env:
          PAT: ${{secrets.PAT}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn install
      - run: yarn generate:site
      - run: yarn checksum
      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './dist'
      - run: npm publish