name: Site

on:
  push:
    branches:
      - next
    paths:
      - "web/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Build App
        run: |
         yarn create:npmrc
         yarn install
         yarn build:site
         yarn generate:site
        env:
          PAT: ${{secrets.PAT}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './web/dist'