name: Extension

on:
  push:
    branches:
      - next
      
jobs:
  build-webview:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Build Query Editor View
        run: |
         yarn create:npmrc
         yarn install
         yarn build:vscode
         yarn generate:vscode
        working-directory: ./views/query-editor
        env:
          PAT: ${{secrets.PAT}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Build Notifications View
        run: |
         yarn install
         yarn build
         yarn generate
        working-directory: ./views/notifications
      - name: Build Extension
        run: |
         yarn install
         yarn build
      - name: Publish Extension on VS Code Marketplace
        uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      - name: Publish Extension on VSX Registry
        env:
          VSX_TOKEN: ${{ secrets.VSX_TOKEN }}
        run: npx ovsx publish -p $VSX_TOKEN
